package:
  name: pyiron_dft
  version: beta

source:
  path: ../../

requirements:
  build:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables
    - ase
    - spglib
    - pyironbase
    - pyiron_atomistics

  run:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables
    - ase
    - spglib
    - pyironbase
    - pyiron_atomistics

test:
  imports:
    - pyiron_dft

about:
  home: http://pyiron.org
  license: BSD
  summary: "pyiron dft plugin"
