version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pyiron-base
    versions:
    - 0.2.0
    - 0.2.11
  - dependency-name: h5py
    versions:
    - 3.2.0
  - dependency-name: phonopy
    versions:
    - 2.9.1
