language: python

env:
  - MINICONDA="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh" PYTHONVER="2.7" USER="pyiron" 
  - MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.5" USER="pyiron"
  - MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.6" USER="pyiron"

install:
  - sudo apt-get update
  - wget ${MINICONDA} -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda info -a
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build git make anaconda-client
  - conda config --set anaconda_upload yes
  - conda config --add channels conda-forge
  - conda config --add channels pyiron

script:
  - conda build --python ${PYTHONVER} --user ${USER} --token ${CONDA_UPLOAD_TOKEN} conda/pyiron_dft

deploy:
  provider: pypi
  user: pyiron
  password:
    secure: P7Hu6El+pW6f1YOaF5mvgu/oW52Sjc4vX3Xnw5A4UbYVl+e23Nmq78jXEfi9eRrE/vfylW6Ix/169e+oCJHuPR8VShEIL0UP8ZAY2xTm5ey7R4+M0Ie0KcJEQmx873pwMmzB+MZ825pSec+Bm0V0WDjIAV03l1/ky4YYvH8H87LbnuLp/St0qRe624j0bJsgdjWET11hKCobNztRSwR5BPo4Z0Guw40LpXAeiEo1M7CUt6LDJ3T0fy4j1GWkjBcfGcS4/HDx9pib6d+Q8bJ2eDXJqeEuQ/S5whjQjAQ0Rn4ZwxrWwf2ta+vUmj+D2c5f8O2fR+qGuXBuZOvUWanRxqwwdAjjtnr2JiW16rWwFq/+zzWtWmEAca01DyekHm9fvfiXuG6LVyT+MVQ8U9QujryIYETpBf+1Ewz+ocNd7c9cxJvm3Xwg8qLUBUDoZqPBdiRAK2IRKHKt+fII2XzpIdJTel4qIL4DY0IQCK0aqzNlgsVU5aEMFRddpWExR5FmHJ/jMDNCJRoXoD+xJedhbqiAznN/iUJFKl/3JhJDKF6ReHlb4SvUysJthU34MwgzSOkIo/jVA/zVLMBH/9XRBA+BJJhm8OLTwE/hg8rghZXXldoAprzOZePNxyFrTmGcfz3EetrLYPFPtre+hLHjqOZl8KUYXazySJFVg6KfBZ4=
