trigger:
  - master

# Set variables once
variables:
  linux: 'ubuntu-16.04'
  mac: 'macos-10.13'
  windows: 'vs2017-win2016'

pr:
  branches:
    include:
      - '*'

jobs:
  - job: 'Test'
    strategy:
      matrix:
        py27-linux:
          imageName: $(linux)
          python.version: '2.7'
        py37-linux:
          imageName: $(linux)
          python.version: '3.7'
        py27-mac:
          imageName: $(mac)
          python.version: '2.7'
        py37-mac:
          imageName: $(mac)
          python.version: '3.7'
        py27-win:
          imageName: $(windows)
          python.version: '2.7'
        py37-win:
          imageName: $(windows)
          python.version: '3.7'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    
    - script: pip install --upgrade pip
      displayName: 'Upgrade pip'

   - script: pip install numpy
      displayName: 'Install numpy'

    - script: pip install --pre .
      displayName: 'Install pyiron'

    - script: echo -e "[DEFAULT]\nTOP_LEVEL_DIRS = $PWD\nRESOURCE_PATHS = $PWD/tests/static" > ~/.pyiron
      displayName: 'create config file'

    - script: coverage run --omit pyiron/_version.py -m unittest discover tests
      displayName: 'run tests'
