channels:
- conda-forge
dependencies:
- jupyterlab=0.33.6
- python
- pyiron
- lammps
- nodejs=9.11.1
- nglview=1.1.5
- ipython=6.5.0 
- ipywidgets=7.3.2 
- notebook=5.6.0 
- ipykernel=4.8.2
# only works for jupyter notebooks - but there still seems to be a bug with jupyterlab - and nglview still has to be installed manually.
# - jupyterlab
# - nodejs
