package:
  name: pyironbase
  version: beta

source:
  path: ../../

requirements:
  build:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables

  run:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables

test:
  imports:
    - pyironbase

about:
  home: http://pyiron.org
  license: BSD
  summary: "pyironbase"
