channels:
- conda-forge
dependencies:
- aimsgb =1.0.1
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib-base =3.7.2
- numpy =1.24.3
- phonopy =2.20.0
- plotly =5.15.0
- pymatgen =2023.5.31
- pyscal =2.10.18
- scikit-learn =1.3.0
- scipy =1.11.1
- spglib =2.0.2
- sqsgenerator =0.2
