channels:
- conda-forge
dependencies:
- nbsphinx
- aimsgb
- ase
- defusedxml
- future
- h5py
- matplotlib-base
- mendeleev
- numpy
- pandas
- phonopy
- pyiron_base
- pymatgen
- pyscal
- pytables
- scipy
- seekpath
- scikit-learn
- spglib
