channels:
  - conda-forge
dependencies:
  - aimsgb =0.1.0
  - ase =3.22.0
  - coveralls
  - coverage
  - codacy-coverage
  - defusedxml =0.7.1
  - future =0.18.2
  - h5py =3.3.0
  - matplotlib-base =3.4.2
  - mendeleev =0.7.0
  - numpy =1.21.1
  - pandas =1.3.0
  - phonopy =2.11.0
  - pyiron_base =0.2.20
  - pymatgen =2022.0.10
  - pyscal =2.10.12
  - pytables =3.6.1
  - scipy =1.7.0
  - seekpath =2.0.1
  - six =1.16.0
  - scikit-learn =0.24.2
  - spglib =1.16.1
