channels:
- conda-forge
dependencies:
- aimsgb =0.1.3
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib-base =3.7.1
- numpy =1.24.3
- phonopy =2.20.0
- pymatgen =2023.5.31
- pyscal =2.10.18
- scikit-learn =1.2.2
- scipy =1.10.1
- spglib =2.0.2
- sqsgenerator =0.2
