channels:
- conda-forge
dependencies:
- aimsgb =1.1.0
- ase =3.22.1
- coverage
- matplotlib-base =3.8.2
- nglview =3.1.1
- numpy =1.26.3
- phonopy =2.21.0
- plotly =5.18.0
- pymatgen =2023.12.18
- pyscal =2.10.18
- pyxtal =0.6.1
- scikit-learn =1.3.2
- scipy =1.11.4
- spglib =2.2.0
- sqsgenerator =0.3
