name: pyiron-structuretoolkit
channels:
- conda-forge
dependencies:
- aimsgb =1.1.1
- ase =3.23.0
- coverage
- dscribe =2.1.1
- matplotlib-base =3.9.2
- nglview =3.1.2
- notebook
- numpy =1.26.4
- phonopy =2.26.6
- plotly =5.24.0
- pymatgen =2024.8.9
- pyscal3 =3.2.7
- pyxtal =1.0.2
- scikit-learn =1.5.1
- scipy =1.14.1
- spglib =2.5.0
- sqsgenerator =0.3
