name: pyiron-structuretoolkit
channels:
- conda-forge
dependencies:
- aimsgb =1.1.1
- ase =3.23.0
- coverage
- dscribe =2.1.1
- matplotlib-base =3.8.4
- nglview =3.1.2
- notebook
- numpy =1.26.4
- phonopy =2.24.3
- plotly =5.22.0
- pymatgen =2024.6.10
- pyscal3 =3.2.3
- pyxtal =0.6.7
- scikit-learn =1.5.0
- scipy =1.14.0
- spglib =2.4.0
- sqsgenerator =0.3
