channels:
- conda-forge
dependencies:
- aimsgb =1.1.0
- ase =3.22.1
- coverage
- dscribe =2.1.0
- matplotlib-base =3.8.2
- nglview =3.1.1
- notebook
- numpy =1.26.4
- phonopy =2.21.1
- plotly =5.18.0
- pymatgen =2024.2.8
- pyscal =2.10.18
- pyxtal =0.6.2
- scikit-learn =1.4.0
- scipy =1.12.0
- spglib =2.3.1
- sqsgenerator =0.3
