channels:
- conda-forge
dependencies:
- aimsgb =1.1.1
- ase =3.22.1
- coverage
- dscribe =2.1.0
- matplotlib-base =3.8.4
- nglview =3.1.2
- notebook
- numpy =1.26.4
- phonopy =2.22.1
- plotly =5.21.0
- pymatgen =2024.5.1
- pyscal =2.10.18
- pyxtal =0.6.2
- scikit-learn =1.4.2
- scipy =1.13.0
- spglib =2.4.0
- sqsgenerator =0.3
