channels:
- conda-forge
dependencies:
- aimsgb =0.1.1
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.7.0
- matplotlib-base =3.5.2
- mendeleev =0.10.0
- numpy =1.23.1
- pandas =1.4.3
- phonopy =2.15.1
- pint =0.19.2
- pyiron_base =0.5.22
- pymatgen =2022.7.25
- pyscal =2.10.15
- scipy =1.9.0
- seekpath =2.0.1
- scikit-learn =1.1.2
- spglib =1.16.5
- ipywidgets < 8
