channels:
  - conda-forge
dependencies:
  - gpaw >=20
  - jupyter
  - lammps
  - nglview
  - papermill
  - seaborn
  - sphinxdft >=2.7.0
  - sphinxdft-data
  - iprpy-data
  - pyiron-data >=0.0.5
  - pymatgen
  - sqsgenerator
