channels:
- conda-forge
dependencies:
- aimsgb =0.1.0
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- defusedxml =0.7.1
- future =0.18.2
- h5py =3.6.0
- matplotlib-base =3.5.1
- mendeleev =0.9.0
- numpy =1.22.1
- pandas =1.4.0
- phonopy =2.12.0
- pyiron_base =0.5.1
- pymatgen =2022.1.20
- pyscal =2.10.15
- pytables =3.6.1
- scipy =1.7.3
- seekpath =2.0.1
- scikit-learn =1.0.2
- spglib =1.16.3
