channels:
- conda-forge
dependencies:
- aimsgb =1.0.2
- ase =3.22.1
- matplotlib-base =3.5.3
- nglview =2.7.7
- numpy =1.23.5
- phonopy =2.20.0
- plotly =4.14.3
- pymatgen =2022.1.24
- pyscal =2.10.4
- scikit-learn =1.2.1
- scipy =1.11.1
- spglib =1.16.5
- sqsgenerator =0.2
- pyxtal =0.5.5
