{% set data = load_setup_py_data() %}

package:
  name: pyiron_base
  version: {{ data.get('version') }}

source:
  path: ../../

requirements:
  build:
    - python
    - h5py
    - h5io
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pathlib2
    - pytables

  run:
    - python
    - h5py
    - h5io
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pathlib2
    - pytables

build:
  noarch: python
  script_env:
   - TRAVIS
   - APPVEYOR

test:
  imports:
    - pyiron_base

about:
  home: http://pyiron.org
  license: BSD
  summary: "pyiron_base"
