package:
  name: pyiron_base
  version: beta

source:
  path: ../../

requirements:
  build:
    - python
    - h5py
    - h5io
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables

  run:
    - python
    - h5py
    - h5io
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables

test:
  imports:
    - pyiron_base

about:
  home: http://pyiron.org
  license: BSD
  summary: "pyiron_base"
