package:
  name: pyiron_atomistics
  version: beta

source:
  path: ../../

requirements:
  build:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables
    - ase
    - spglib
    - pyiron_base

  run:
    - python
    - h5py
    - matplotlib
    - numpy
    - pandas
    - six
    - sqlalchemy
    - pytables
    - ase
    - spglib
    - pyiron_base

build:
  script_env:
   - TRAVIS
   - APPVEYOR

test:
  imports:
    - pyiron_atomistics

about:
  home: http://pyiron.org
  license: BSD
  summary: "pyiron atomistics plugin"
