channels:
- conda-forge
dependencies:
- ipykernel
- nbsphinx
- aimsgb =1.1.0
- ase =3.22.1
- coverage
- codacy-coverage
- matplotlib-base =3.8.0
- nglview =3.0.8
- numpy =1.26.0
- phonopy =2.20.0
- plotly =5.17.0
- pymatgen =2023.10.4
- pyscal =2.10.18
- scikit-learn =1.3.0
- scipy =1.11.3
- spglib =2.0.2
- sqsgenerator =0.3
