# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Merge Environments
      shell: bash -l {0}
      run: |
        awk 'NR>3{ print $0 }' .ci_support/environment-docs.yml >> .ci_support/environment.yml
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "0.17.0"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true  
        environment-file: .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        pip install --no-deps .
        conda list
    - name: Documentation
      shell: bash -l {0}
      run: ./.ci_support/build_docs.sh
