# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Notebooks for Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [labeled, opened, synchronize]

jobs:
  build:
    if: |
      ${{ github.event.type == 'PushEvent' ||
          ( github.event.type == 'PullRequestEvent'  && contains(github.event.pull_request.labels.*.name, 'integration' ))
       }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Merge Environments
      shell: bash -l {0}
      run: |
        awk 'NR>3{ print $0 }' .ci_support/environment-notebooks.yml >> .ci_support/environment.yml
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "0.17.0"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true  
        environment-file: .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        pip install --no-deps .
    - name: Tests
      shell: bash -l {0}
      run: ./.ci_support/build_integration_notebooks.sh
