# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integration Tests using Unittest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    if: |
      github.event_name == 'push' ||
      ( github.event_name == 'pull_request'  && contains(github.event.pull_request.labels.*.name, 'integration' ))

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Merge Environments
      shell: bash -l {0}
      run: |
        awk 'NR>3{ print $0 }' .ci_support/environment-notebooks.yml >> .ci_support/environment.yml
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true  
        environment-file: .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
    - name: Tests
      shell: bash -l {0}
      run: coverage run --omit pyiron_atomistics/_version.py -m unittest discover test_integration
