# This workflow is used to run the unittest of pyiron

name: MMinimal Installation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
        cp .ci_support/environment.yml environment.yml
        sed -i '/aimsgb/d' environment.yml
        sed -i '/phonopy/d' environment.yml
        sed -i '/pymatgen/d' environment.yml
        sed -i '/pyscal/d' environment.yml
        sed -i '/scikit-learn/d' environment.yml
        sed -i '/spglib/d' environment.yml
        sed -i '/sqsgenerator/d' environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.11'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        use-mamba: true
    - name: Update environment
      run: mamba env update -n my-env -f environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: python -m unittest discover tests
