# This workflow is used to run the unittest of pyiron

name: Minimal Installation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  mini-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pyiron/actions/unit-test@main
      with:
        python-version: '3.11'
        env-prefix: /usr/share/miniconda3/envs/my-env
        env-label: linux-64-py-3-11
        env-files: .ci_support/environment_mini.yml
        test-dir: test/unit
    timeout-minutes: 30

  mini-benchmark-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pyiron/actions/unit-test@main
      with:
        python-version: '3.11'
        env-prefix: /usr/share/miniconda3/envs/my-env
        env-label: linux-64-py-3-11
        env-files: .ci_support/environment_mini.yml
        test-dir: test/benchmark
    timeout-minutes: 30

  mini-integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pyiron/actions/unit-test@main
      with:
        python-version: '3.11'
        env-prefix: /usr/share/miniconda3/envs/my-env
        env-label: linux-64-py-3-11
        env-files: .ci_support/environment_mini.yml
        test-dir: test/integration
    timeout-minutes: 30
